# Generated by Django 4.2.2 on 2023-06-15 12:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="is_resolved",
        ),
    ]
