# Generated by Django 4.1.7 on 2023-07-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_additionalapplicnats_additionalassistance_apps_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="active_status",
            field=models.BooleanField(default=False),
        ),
    ]
