# Generated by Django 4.1.7 on 2023-07-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_customuser_financialstatus_customuser_mortgageamount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='name',
        ),
    ]
